#pragma once

#include "execution/matching_engine.hpp"
#include "portfolio/portfolio.hpp"
#include "types.hpp"

#include <functional>
#include <vector>

namespace hft::strategy {

/**
 * @brief Exposes matching, portfolio, and market state to a strategy.
 */
class StrategyContext {
public:
  using FillSink = std::function<void(const Fill &fill, StrategyContext &ctx)>;

  /**
   * @brief Creates a context over existing engine and portfolio objects.
   * @param engine Non-owning matching engine pointer.
   * @param portfolio Non-owning portfolio pointer.
   */
  StrategyContext(execution::MatchingEngine *engine,
                  portfolio::Portfolio *portfolio) noexcept;

  /**
   * @brief Sets the sink invoked for fills created through the context.
   * @param sink Fill sink callback to store.
   */
  void setFillSink(FillSink sink);

  /**
   * @brief Sets the latest book snapshot.
   * @param book Input book snapshot that must outlive this context use.
   */
  void setBook(const LOBData &book) noexcept;

  /**
   * @brief Sets the current strategy timestamp.
   * @param ts Input timestamp.
   */
  void setNow(Timestamp ts) noexcept;

  /**
   * @brief Places a limit order through the matching engine.
   * @param side Order side.
   * @param price Limit price.
   * @param amount Order amount.
   * @return New order id, or INVALID_ORDER_ID when placement fails.
   */
  OrderId placeLimit(Side side, double price, double amount);

  /**
   * @brief Executes a market order through the matching engine.
   * @param side Market order side.
   * @param amount Requested market order amount.
   * @return Fills generated by the market order.
   */
  std::vector<Fill> executeMarket(Side side, double amount);

  /**
   * @brief Cancels one active order.
   * @param id Order id to cancel.
   * @return True when an active order was cancelled.
   */
  bool cancel(OrderId id);

  /**
   * @brief Cancels all active orders.
   */
  void cancelAll();

  /**
   * @brief Cancels all active orders on one side.
   * @param side Side whose orders are cancelled.
   */
  void cancelSide(Side side);

  /**
   * @brief Returns all active orders.
   * @return Vector of active orders.
   */
  std::vector<LimitOrder> activeOrders() const;

  /**
   * @brief Returns all active orders on one side.
   * @param side Side used to filter active orders.
   * @return Vector of active orders on the requested side.
   */
  std::vector<LimitOrder> activeOrders(Side side) const;

  /**
   * @brief Returns the number of active orders.
   * @return Active order count.
   */
  std::size_t activeCount() const;

  /**
   * @brief Returns the current strategy timestamp.
   * @return Current timestamp.
   */
  Timestamp now() const noexcept { return now_; }

  /**
   * @brief Checks whether a book snapshot is available.
   * @return True when a book snapshot has been set.
   */
  bool hasBook() const noexcept { return book_ != nullptr; }

  /**
   * @brief Returns the latest book snapshot.
   * @return Reference to the latest book snapshot.
   */
  const LOBData &book() const noexcept { return *book_; }

  /**
   * @brief Returns the best bid price.
   * @return Best bid price, or zero when unavailable.
   */
  double bestBid() const noexcept;

  /**
   * @brief Returns the best ask price.
   * @return Best ask price, or zero when unavailable.
   */
  double bestAsk() const noexcept;

  /**
   * @brief Returns displayed size at the best bid.
   * @return Best bid size, or zero when unavailable.
   */
  double bidSize() const noexcept;

  /**
   * @brief Returns displayed size at the best ask.
   * @return Best ask size, or zero when unavailable.
   */
  double askSize() const noexcept;

  /**
   * @brief Returns the current mid price.
   * @return Mid price, or zero when unavailable.
   */
  double mid() const noexcept;

  /**
   * @brief Returns the current top-of-book microprice.
   * @return Microprice, or mid price when sizes are unavailable.
   */
  double microprice() const noexcept;

  /**
   * @brief Returns the current bid-ask spread.
   * @return Spread, or zero when unavailable.
   */
  double spread() const noexcept;

  /**
   * @brief Returns portfolio cash.
   * @return Current cash balance.
   */
  double cash() const noexcept { return portfolio_->cash(); }

  /**
   * @brief Returns portfolio inventory.
   * @return Current signed inventory.
   */
  double inventory() const noexcept { return portfolio_->inventory(); }

  /**
   * @brief Returns portfolio realized profit and loss.
   * @return Realized profit and loss.
   */
  double realizedPnL() const noexcept { return portfolio_->realizedPnL(); }

  /**
   * @brief Returns portfolio turnover.
   * @return Gross traded notional.
   */
  double turnover() const noexcept { return portfolio_->turnover(); }

  /**
   * @brief Returns total profit and loss marked at the current mid price.
   * @return Total profit and loss.
   */
  double totalPnL() const noexcept;

private:
  execution::MatchingEngine *engine_{nullptr};
  portfolio::Portfolio *portfolio_{nullptr};
  FillSink fill_sink_;
  const LOBData *book_{nullptr};
  Timestamp now_{0};

  /**
   * @brief Returns displayed queue ahead at a side and price.
   * @param side Book side to inspect.
   * @param price Price level to inspect.
   * @return Queue amount ahead at the level, or zero when unavailable.
   */
  double queueAheadAt(Side side, double price) const noexcept;
};

}
