#pragma once

#include "types.hpp"

#include <cstddef>
#include <deque>
#include <functional>
#include <map>
#include <unordered_map>
#include <vector>

namespace hft::execution {

/**
 * @brief Simulates resting orders and fills against external market data.
 */
class MatchingEngine {
public:
  using FillHandler = std::function<void(const Fill &)>;

  /**
   * @brief Posts a simulated limit order.
   * @param side Order side.
   * @param price Limit price.
   * @param amount Order amount.
   * @param ts Placement timestamp.
   * @param queueAhead External queue amount ahead of the order.
   * @return New order id, or INVALID_ORDER_ID when inputs are invalid.
   */
  OrderId placeLimit(Side side, double price, double amount, Timestamp ts,
                     double queueAhead = 0.0);

  /**
   * @brief Cancels one active order.
   * @param id Order id to cancel.
   * @return True when an active order was cancelled.
   */
  bool cancel(OrderId id);

  /**
   * @brief Cancels all active orders.
   */
  void cancelAll();

  /**
   * @brief Cancels all active orders on one side.
   * @param side Side whose orders are cancelled.
   */
  void cancelSide(Side side);

  /**
   * @brief Matches resting orders against an aggressive trade print.
   * @param trade Input trade print.
   * @return Fills generated by the trade.
   */
  std::vector<Fill> onTrade(const TradeData &trade);

  /**
   * @brief Fills resting orders that cross an external book snapshot.
   * @param book Input external book snapshot.
   * @return Fills generated by crossed orders.
   */
  std::vector<Fill> onBookUpdate(const LOBData &book);

  /**
   * @brief Executes a synthetic market order against external book levels.
   * @param side Market order side.
   * @param amount Requested market order amount.
   * @param book Input external book snapshot.
   * @param ts Execution timestamp.
   * @return Taker fills generated by walking the book.
   */
  std::vector<Fill> executeMarket(Side side, double amount,
                                  const LOBData &book, Timestamp ts);

  /**
   * @brief Returns all active orders.
   * @return Vector of active orders.
   */
  std::vector<LimitOrder> activeOrders() const;

  /**
   * @brief Returns all active orders on one side.
   * @param side Side used to filter active orders.
   * @return Vector of active orders on the requested side.
   */
  std::vector<LimitOrder> activeOrders(Side side) const;

  /**
   * @brief Returns the number of active orders.
   * @return Active order count.
   */
  std::size_t activeCount() const noexcept { return orders_.size(); }

private:
  using BidLevels =
      std::map<double, std::deque<OrderId>, std::greater<double>>;
  using AskLevels = std::map<double, std::deque<OrderId>>;

  /**
   * @brief Removes an order id from side-specific price levels.
   * @param order Order to erase from level containers.
   */
  void eraseFromLevels(const LimitOrder &order);

  /**
   * @brief Matches a sell aggressor against resting bids.
   * @param trade Input sell-aggressor trade.
   * @param[in,out] remainingTrade Remaining trade amount to match.
   * @param[out] fills Fills generated by matching.
   */
  void matchSellAggressor(const TradeData &trade, double &remainingTrade,
                          std::vector<Fill> &fills);

  /**
   * @brief Matches a buy aggressor against resting asks.
   * @param trade Input buy-aggressor trade.
   * @param[in,out] remainingTrade Remaining trade amount to match.
   * @param[out] fills Fills generated by matching.
   */
  void matchBuyAggressor(const TradeData &trade, double &remainingTrade,
                         std::vector<Fill> &fills);

  /**
   * @brief Logs diagnostic information for an unmatched trade.
   * @param trade Input trade print.
   */
  void logTradeNoFillHints(const TradeData &trade) const;

  /**
   * @brief Fills resting bids crossed by external asks.
   * @param book Input external book snapshot.
   * @param[out] fills Fills generated by crossed bids.
   */
  void uncrossBidsWithExternalAsks(const LOBData &book,
                                   std::vector<Fill> &fills);

  /**
   * @brief Fills resting asks crossed by external bids.
   * @param book Input external book snapshot.
   * @param[out] fills Fills generated by crossed asks.
   */
  void uncrossAsksWithExternalBids(const LOBData &book,
                                   std::vector<Fill> &fills);

  /**
   * @brief Logs diagnostic information for unfilled crossed orders.
   * @param book Input external book snapshot.
   */
  void logBookUncrossHints(const LOBData &book) const;

  OrderId next_id_{1};
  std::unordered_map<OrderId, LimitOrder> orders_;
  BidLevels bids_;
  AskLevels asks_;
};

}
